name: Generate Pacman Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Generate pacman SVG
        uses: lowlighter/metrics@latest
        with:
          user: JonasMacielWork
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: pacman.svg
          committer_branch: output
          committer_message: "chore: update pacman animation"
          base: header
          plugin_pacman: yes
