name: WakaTime Stats

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_PAT }}
          BLOCKS: " -> ░▒▓█"
          SHOW_TITLE: "true"
          SHOW_TOTAL_CODE_TIME: "true"
          LANG_COUNT: "8"
