name: WakaTime Stats Debug

on:
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Ensure README has waka section (manually!)
        run: |
          grep -q "<!--START_SECTION:waka-->" README.md || echo "⚠️ README.md precisa da seção <!--START_SECTION:waka-->"

      - name: Update README with WakaTime stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_PAT }}
          TIME_RANGE: "all_time"
          SHOW_TITLE: "true"
          TARGET_PATH: "README.md"
          COMMIT_MESSAGE: "chore: update wakatime stats"

      - name: Display README.md content for debugging
        run: |
          echo "--- START of README.md ---"
          cat README.md
          echo "--- END of README.md ---"
